name: Podmienia niepoprawne znaki w nazwach plików
on:
 pull_request

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
       with:
        ref: ${{ github.event.pull_request.head.ref }}
     - name: Poprawienie znaków
       shell: bash
       run: |
          sudo apt-get install rename -y &&
          prename --version &&
          shopt -s globstar &&
          prename -n 's/ą/a/g' ./source/**/*.md &&
          prename -n 's/ć/c/g' ./source/**/*.md &&
          prename -n 's/ę/e/g' ./source/**/*.md &&
          prename -n 's/ł/l/g' ./source/**/*.md &&
          prename -n 's/ń/n/g' ./source/**/*.md &&
          prename -n 's/ó/o/g' ./source/**/*.md &&
          prename -n 's/ś/s/g' ./source/**/*.md &&
          prename -n 's/ź/z/g' ./source/**/*.md &&
          prename -n 's/ż/z/g' ./source/**/*.md &&
          prename -n 's/_/-/g' ./source/**/*.md &&
          prename 'y/A-Z/a-z/' ./source/**/*.md
     - name: Sprawdzanie niepoprawialnych znaków
       shell: bash
       run: for file in $( ls ./source/**/*.md ); do if ! [[ "$( awk -F/ '{ print $NF}' <<< $file )" =~ ^[a-z0-9-].+\.md$ ]]; then echo $file; exit 1; fi; done;
     - name: Commit & push
       uses: stefanzweifel/git-auto-commit-action@v4
       with:
          commit_message: 'Automatycznie poprawione znaki'
          file_pattern: source/**/*.md
          skip_dirty_check: false
