name: Aktualizuje niepoprawne znaki w nazwach plików
on:
 pull_request
env:
  LANG: "pl_PL.UTF-8"
  LANGUAGE: "pl_PL:pl"
  LC_ALL: "pl_PL.UTF-8"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Zamiana polskich znaków
        shell: bash
        run: |
          sudo apt-get update && sudo apt-get install tzdata locales -y && sudo locale-gen pl_PL.UTF-8
          sudo localectl set-locale LANG="pl_PL.UTF-8"
          export LANG="pl_PL.UTF-8"
          sudo update-locale
          setxkbmap pl
          
          echo "Testing language settings"
          echo "All languages..."
          locale -a
          echo "Actual locale"
          locale
          echo "Actual numeric settings"
          locale -c -k LC_NUMERIC
          echo "LANG Variable"
          echo "$LANG"
          echo "LocaleCtl"
          localectl status
          echo "ŚĆĄĆŻŹĆĘ"
          
          ls -aq ./source/**/*.md
          ls -b ./source/**/*.md
          
