name: Aktualizuje niepoprawne znaki w nazwach plików
on:
 pull_request

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Zamiana polskich znaków
        shell: bash
        run: |
         sudo locale-gen pl_PL.UTF-8
         sudo update-locale LANG=pl_PL.UTF-8
         sudo apt-get install -y rename && shopt -s globstar && rename 's/ś/s/g' ./source/**/*.md && ls ./source/**/*.md && git status
