name: Aktualizuje niepoprawne znaki w nazwach plików
on:
 pull_request

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2
     - name: Zamiana polskich znaków
       shell: bash
       run: |
          ls source/_publikacje/*
          echo "AA"
          git ls-files
          
