name: Aktualizuje niepoprawne znaki w nazwach plików
on:
 pull_request

jobs:
  update:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Zamiana polskich znaków
        shell: bash
        run: >
         shopt -s globstar && rename 's/ś/s/g' ./source/**/*.md && git status
