name: Aktualizuje niepoprawne znaki w nazwach plików
on:
 pull_request
env:
  LANG: "pl_PL.UTF-8"
  LANGUAGE: "pl_PL:pl"
  LC_ALL: "pl_PL.UTF-8"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Zamiana polskich znaków
        shell: bash
        run: |
         sudo locale-gen ${{ env.LANG }}
         sudo update-locale LANG=${{ env.LANG }}
         dpkg-reconfigure locale 
         LANG=pl_PL.UTF-8 ls ./source/**/*.md
