name: Aktualizuje niepoprawne znaki w nazwach plików
on:
 pull_request

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
         fetch-depth: 0
      - name: Zamiana polskich znaków
        shell: bash
        run: >
         sudo apt-get install -y rename && rename --version
