# This is a basic workflow to help you get started with Actions

name: UzupelnianieDat

# Controls when the action will run. 
on:
 pull_request:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
        fetch-depth: 0
      
      - uses: php-actions/composer@v6
        with:
          php_version: '7.4'

      - uses: nanasess/setup-php@master
        with:
          php-version: '7.4'
      - run: php postprocess.php $( git diff origin/${{ github.event.pull_request.base.ref }}..origin/${{ github.event.pull_request.head.ref }} --name-status | grep -i '^M' | awk -F ' ' '{print $2}' | grep -i '.md' | grep -i 'source/' )
          
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Optional but recommended
          # Defaults to "Apply automatic changes"
          commit_message: 'Uzupełnienie dat w treściach'
          
          file_pattern: source/**

          # Optional: Disable dirty check and always try to create a commit and push
          skip_dirty_check: false
